#!/usr/local/bin/perl
# 
#
# Copyright (c) 2017, 2021, Oracle and/or its affiliates. 
#
#    NAME
#      usmvsn.pm - usmversion define for perl scripts usage. 
#
#    DESCRIPTION
#      $LIBMAJVSN - Library major version defined by rdbms
#
#    NOTES
#      This file is automatically generated at build time.
#
# 

use strict;
package usmvsn;
require Exporter;

our @ISA = qw (Exporter);
our @EXPORT = qw (vsn_getmaj
                  %USMVSN);

our $LIBMAJVSN = "19";
our %USMVSN = (
    "MAJORVSN"      => "19",
    "MINORVSN"      => "0",
    "MIDTIERVSN"    => "0",
    "PATCHMAJVSN"   => "0",
    "PATCHMINVSN"   => "0",
    "FULLMAJVSN"    => "19",
    "FULLRUVSN"     => "7",
    "FULLRURVSN"    => "0",
    "FULLINCVSN"    => "0",
    "FULLEXTVSN"    => "0",
    );

sub vsn_getmaj
{
    return $LIBMAJVSN;
}
